import {
  X,
  Y,
  Z,
  ease,
  blend,
  box,
  capped_cone,
  capped_cylinder,
  capsule,
  circle,
  cylinder,
  dodecahedron,
  ellipsoid,
  equilateral_triangle,
  hexagon,
  icosahedron,
  intersection,
  line,
  octahedron,
  plane,
  polygon,
  pyramid,
  rectangle,
  rounded_box,
  rounded_cone,
  rounded_cylinder,
  rounded_rectangle,
  rounded_x,
  slab,
  slab2,
  sphere,
  tetrahedron,
  torus,
  union,
  vesica,
  wireframe_box,
  type SDF2,
  type SDF3,
} from "./index";
import { mul } from "../core/math";

export const unsupportedOriginalApi = [
  "text",
  "image",
  "measure_text",
  "measure_image",
  "Mesh",
  "Mesh.from_file",
  "Mesh.sdf",
] as const;

export const supportedSummary = {
  moduleExports: 47,
  sdf2Methods: 17,
  sdf3Methods: 28,
};

export function buildApiCompletenessFixtures(): { two: SDF2[]; three: SDF3[] } {
  const two = [
    circle(),
    line(),
    slab2({ x0: -1, x1: 1, y0: -1, y1: 1 }),
    rectangle(1),
    rounded_rectangle([1, 2], [0.1, 0.2, 0.3, 0.4]),
    equilateral_triangle(),
    hexagon(1),
    rounded_x(1, 0.1),
    polygon([[0, 0], [1, 0], [0.5, 1]]),
    vesica(1, 0.5),
  ];

  const twoOps = [
    two[0].translate([1, 0]),
    two[1].scale([1, 2]),
    two[2].rotate(Math.PI / 4),
    two[3].circular_array(6),
    two[4].elongate([0.2, 0.3]),
    two[5].repeat([1, 1], [2, 2], 1),
    union(two[6], two[7]) as SDF2,
    intersection(two[6], two[7]) as SDF2,
    two[6].difference(two[7]),
    blend(two[6], two[7]) as SDF2,
    two[8].negate(),
    two[8].dilate(0.1),
    two[8].erode(0.1),
    two[8].shell(0.05),
  ];

  const three = [
    sphere(),
    plane(),
    slab({ x0: -1, x1: 1, y0: -1, y1: 1, z0: -1, z1: 1 }),
    box(1),
    box({ a: [-1, -1, -1], b: [1, 1, 1] }),
    rounded_box([1, 2, 3], 0.1),
    wireframe_box([1, 2, 3], 0.05),
    torus(1, 0.2),
    capsule(mul(Z, -1), Z, 0.2),
    cylinder(0.5),
    capped_cylinder(mul(Z, -1), Z, 0.5),
    rounded_cylinder(0.5, 0.1, 1),
    capped_cone(mul(Z, -1), Z, 0.8, 0.2),
    rounded_cone(0.8, 0.2, 1),
    ellipsoid([1, 2, 3]),
    pyramid(1),
    tetrahedron(1),
    octahedron(1),
    dodecahedron(1),
    icosahedron(1),
    two[0].extrude(1),
    two[1].extrude_to(two[2], 1, ease.in_out_quad),
    two[3].revolve(1),
  ];

  const threeOps = [
    three[0].translate([1, 2, 3]),
    three[1].scale([1, 2, 3]),
    three[2].rotate(Math.PI / 4, X),
    three[3].rotate_to(Z, X),
    three[4].orient(Y),
    three[5].circular_array(8, 2),
    three[6].elongate([0.1, 0.2, 0.3]),
    three[7].twist(0.5),
    three[8].bend(0.5),
    three[9].bend_linear(mul(Z, -1), Z, X, ease.in_out_quad),
    three[10].bend_radial(0.2, 1, 0.4, ease.out_quad),
    three[11].transition_linear(three[12], mul(Z, -1), Z, ease.in_out_sine),
    three[13].transition_radial(three[14], 0, 2, ease.in_quad),
    three[15].wrap_around(-1, 1),
    three[16].slice().extrude(0.1),
    three[17].repeat([1, 1, 1], [2, 2, 2], 1),
    union(three[18], three[19]) as SDF3,
    intersection(three[18], three[19]) as SDF3,
    three[18].difference(three[19]),
    blend(three[18], three[19]) as SDF3,
    three[20].negate(),
    three[20].dilate(0.1),
    three[20].erode(0.1),
    three[20].shell(0.05),
  ];

  return { two: [...two, ...twoOps], three: [...three, ...threeOps] };
}
